version: '3.8'
services:
  master:
    image: locust_local:1.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: locust --config=/locust/master.conf --html=/locust/report.html
    container_name: locust_master
    ports:
      - "8089:8089"
    volumes:
      - ./locust:/locust

  test_api:
    image: locust_local_api:1.0
    build:
      context: .
      dockerfile: ./Dockerfile_api
    container_name: locust_test_api

  worker:
    image: locust_local:1.0
    depends_on:
      - master
    command: locust --config=/locust/worker.conf --master-host master
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./locust:/locust
